name: Update Product Formula in Tap
# This workflow will automatically update our product formulae on the release of
# new versions
on:
  repository_dispatch:
    types: [version-updated]

jobs:
  update-formula:
    name: Update Formula
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      -
        name: Generate new formula
        run: |
          sleep 10
          cat /etc/os-release
          sleep 5
          echo ${{github.event.client_payload.name}}
          echo ${{github.event.client_payload.version}}
      
