name: Update Product Formula in Tap
# This workflow will automatically update our product formulae on the release of
# new versions
on:
  repository_dispatch:
    types: [version-updated]

jobs:
  update-formula:
    name: Update Formula
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      -
        name: Build formula_templater CLI
        run: |
          cd util/formula_templater && go build
      -
        name: Generate new formula
        if: ${{ github.event.client_payload.cask == 'false' }}
        run: |
          ./util/formula_templater/formula_templater ${{github.event.client_payload.name}} ${{github.event.client_payload.version}} ./util/formula_templater/config.hcl > ./Formula/${{github.event.client_payload.name}}.rb
